
spring:
  application:
    name: TestSwoyo
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testSwoyo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 678594
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    locations: classpath:db/migration
